seed: 42
no_gpu: False
env: "coffee-push-v2"
output:
  location: "$HOME/CorrectiveIL/output/"
  folder_suffix: ""
data:
  expert: None
  pkl: 'data/metaworld-coffee-push-v2_50.pkl'
  num_traj: '...'
  horizon: '...'
  num_datapoints: '...'
dynamics:
  lipschitz_type: "spectral_normalization"
  lipschitz_constraint: 4.0
  lr: 0.001
  weight_decay: 0.00001
  layers: [512, 512]
  activation: relu
  train_epochs: 100
  batch_size: 512
  val_percentage: 1
aug:
  type: 'backward_euler_fast'
  max_iter: 50
  num_labels: 10
  delta: 0.00001
  label_err_quantile: 0.5
  use_expert_label: False
policy:
  naive: False
  noise_bc: 0.0
  lr: 0.001
  batch_size: 512
  train_epochs: 200
eval:
  noise: [0.0003]
