seed: 42
no_gpu: False
env: "drawer-close-v2"
output:
  location: "output/"
  folder_suffix: ""
data:
  expert: None
  pkl: 'data/metaworld-drawer-close-v2.pkl'
  num_traj: '...'
  horizon: '...'
  num_datapoints: '...'
dynamics:
  lipschitz_type: "soft_sampling"
  lipschitz_constraint: 3.0
  soft_lipschitz_penalty_weight: 0.0005
  soft_lipschitz_sampling_eps: 0.0003
  soft_lipschitz_n_samples: 5
  lr: 0.001
  weight_decay: 0.00001
  layers: [512, 512]
  activation: relu
  train_epochs: 250
  batch_size: 512
  val_percentage: 1
aug:
  type: 'forward_euler'
  max_iter: 50
  num_labels: 10
  delta: 0.00001
  epsilon:  10.0
  use_expert_label: False
policy:
  naive: False
  noise_bc: 0.0
  lr: 0.001
  batch_size: 512
  train_epochs: 200
eval:
  noise: [0.0003]
