seed: 42
no_gpu: False
env: "walker2d-expert-v2"
output:
  location: "output/"
  folder_suffix: ""
data:
  expert: None
  pkl: 'data/walker2d-expert-v2_20.pkl'
  num_traj: '...'
  horizon: '...'
  num_datapoints: '...'
dynamics:
  lipschitz_type: spectral_normalization
  slack_weight: 1
  lipschitz_constraint: 2.0
  soft_lipschitz_penalty_weight: 0.0005
  soft_lipschitz_sampling_eps: 0.0003
  soft_lipschitz_n_samples: 5
  lr: 0.001
  weight_decay: 0.00001
  layers: [512, 512]
  activation: relu
  train_epochs: 200
  batch_size: 512
  val_percentage: 1
aug:
  type: 'backward_euler_fast'
  max_iter: 50
  num_labels: 20
  delta: 0.00001
  label_err_quantile: 0.1
  use_expert_label: False
policy:
  naive: False
  noise_bc: 0.0
  lr: 0.001
  batch_size: 512
  train_epochs: 200
eval:
  noise: [0.03]
